import type { Metadata } from "next";
import NextAuthProvider from "@/providers/next-auth-provider";
import NextThemeProvider from "@/providers/them-provider";
import "./globals.css";
import GlobalState from "@/context";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "STSBlog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-serif dark:bg-dark">
        <NextThemeProvider>
          <NextAuthProvider>
            <GlobalState>
              <Header />
              {children}
            </GlobalState>
          </NextAuthProvider>
        </NextThemeProvider>
      </body>
    </html>
  );
}
